security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: admin
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

#spring:
#  data:
#    mongodb:
#      host: 116.196.118.169
#      username: user
#      password: admin
#      database: piggymetrics
#      port: 27017

server:
  servlet:
    context-path: /account
  port: 6000

spring:
  datasource:
    url: jdbc:mysql://10.0.1.134:3306/sun_ftdm3
    username: root
    password: Sunyard88
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari.minimum-idle: 5
    hikari.maximum-pool-size: 15
    hikari.connection-test-query: SELECT 1
    hikari.max-lifetime: 1800000
    hikari.connection-timeout: 30000
    hikari.pool-name: DatebookHikariCP
    hikari.auto-commit: true
  redis:
    jedis:
      pool:
        max-active: 10
        min-idle: 5
        max-idle: 20
        max-wait: 5000
    host: 10.0.1.134
    port: 6379
    password: sunyard123
    timeout: 300

mybatis:
  typeAliasesPackage: com.piggymetrics.account.dao.entity
  mapperLocations: classpath*:com/piggymetrics/account/dao/mapper/xml/*.xml