security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: admin
      accessTokenUri: http://10.0.1.134:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: 116.196.118.169
      username: user
      password: admin
      database: piggymetrics
      port: 27017

server:
  servlet:
    context-path: /accounts
  port: 6000
