logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://10.0.1.134:8761/eureka/,http://172.16.35.20:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://10.0.1.134:5000/uaa/users/current

spring:
  rabbitmq:
    host: 10.0.1.134
    username: ftdm
    password: ftdm@sunyard
    port: 5672
    virtual-host: /ftdm