spring:
  data:
    mongodb:
      host: 116.196.118.169
      username: user
      password: admin
      database: piggymetrics
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000
